version: '3'

services:
  app:
    image: node:14-alpine
    command: sh -c "npm install && npm run build && npm run start"
    ports:
      - 80:80
    working_dir: /app
    environment:
      NODE_ENV: production
      PORT: 80
    logging:
      driver: awslogs
      options:
        awslogs-group: ec2-tutorial
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: web
